package hospital.UI;

import java.sql.*;

/**
 *
 * @author andres
 */
public class FormPrin extends javax.swing.JFrame {

    // <editor-fold defaultstate="collapsed" desc="Atributos de la clase">
    public final String SERVIDOR = "localhost";
    public final String PUERTO = "3306";
    public final String BASE_DATOS = "Hospital";
    public final String USUARIO = "root";
    public final String CONTRASENHA = "";
    
    private Connection conexionBD;

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Constructores de la clase">
    public FormPrin() {
        initComponents();
        this.setTitle("Hospitalator: Gestión de hospitales");
        this.setLocation(300, 50);
        this.setSize(1000, 750);
    }
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menujMantenimientos = new javax.swing.JMenu();
        opcionPacientes = new javax.swing.JMenuItem();
        opcionMedicos = new javax.swing.JMenuItem();
        opcionDiagnosticos = new javax.swing.JMenuItem();
        opcionVisitasMedicas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcionCamas = new javax.swing.JMenuItem();
        opcionHabitaciones = new javax.swing.JMenuItem();
        opcionSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/images/imagenBienvenida.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        menujMantenimientos.setText("Mantenimientos");

        opcionPacientes.setText("Pacientes");
        opcionPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionPacientesMousePressed(evt);
            }
        });
        menujMantenimientos.add(opcionPacientes);

        opcionMedicos.setText("Médicos");
        opcionMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionMedicosMousePressed(evt);
            }
        });
        menujMantenimientos.add(opcionMedicos);

        opcionDiagnosticos.setText("Diagnósticos");
        opcionDiagnosticos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionDiagnosticosMousePressed(evt);
            }
        });
        menujMantenimientos.add(opcionDiagnosticos);

        opcionVisitasMedicas.setText("Visitas Médicas");
        menujMantenimientos.add(opcionVisitasMedicas);
        menujMantenimientos.add(jSeparator1);

        opcionCamas.setText("Camas");
        opcionCamas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionCamasMousePressed(evt);
            }
        });
        menujMantenimientos.add(opcionCamas);

        opcionHabitaciones.setText("Habitaciones");
        opcionHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionHabitacionesMousePressed(evt);
            }
        });
        menujMantenimientos.add(opcionHabitaciones);

        jMenuBar1.add(menujMantenimientos);

        opcionSalir.setText("Salir");
        opcionSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opcionSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(opcionSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Eventos del formulario">    
    private void opcionSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionSalirMousePressed
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_opcionSalirMousePressed

    private void opcionPacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionPacientesMousePressed
        // TODO add your handling code here:

        FormListPacientes formulario;
        
        formulario = new FormListPacientes(conexionBD, this, true);
        formulario.setVisible(true);
        

    }//GEN-LAST:event_opcionPacientesMousePressed

    private void opcionMedicosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionMedicosMousePressed
        // TODO add your handling code here:

        FormListMedicos formulario;
        
        formulario = new FormListMedicos(this.conexionBD, this, true);
        formulario.setVisible(true);

    }//GEN-LAST:event_opcionMedicosMousePressed

    private void opcionDiagnosticosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionDiagnosticosMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_opcionDiagnosticosMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        conexionBD = conectarBD(SERVIDOR, PUERTO, BASE_DATOS, USUARIO, CONTRASENHA);
        if (conexionBD == null) {
            System.out.println("No se ha podido conectar a la Base de Datos");
            this.dispose();
        }

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (conexionBD != null) {
            this.cerrarConexionBD();
        }
    }//GEN-LAST:event_formWindowClosing

    private void opcionCamasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionCamasMousePressed
        // TODO add your handling code here:
        FormListCamas formulario;

        formulario = new FormListCamas(this.conexionBD, this, true);
        formulario.setVisible(true);
    }//GEN-LAST:event_opcionCamasMousePressed

    private void opcionHabitacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionHabitacionesMousePressed
        // TODO add your handling code here:
        FormListHabitaciones formulario;

        formulario = new FormListHabitaciones(this.conexionBD, this, true);
        formulario.setVisible(true);
    }//GEN-LAST:event_opcionHabitacionesMousePressed
    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Métodos de Conexión a la Base de Datos">
    public Connection conectarBD(String direccionServer, String puertoServer,
            String baseDatos, String usuario, String password) {
        Connection devolucion;
        String cadenaConexion;
        
        try {
            
            cadenaConexion = "jdbc:mysql://" + direccionServer + ":" + puertoServer + "/" + baseDatos;
            
            devolucion = conectarBD("com.mysql.cj.jdbc.Driver", cadenaConexion, usuario, password);
            
        } catch (Exception ex) {
            devolucion = null;
        }
        
        return devolucion;
    }
    
    public Connection conectarBD(String PDriver, String PCadena_Conexion,
            String PUsuario, String PContrasenha) {
        Connection VDevolucion;
        
        try {
            Class.forName(PDriver);
            VDevolucion = DriverManager.getConnection(PCadena_Conexion, PUsuario, PContrasenha);
        } catch (Exception ex) {
            VDevolucion = null;
        }
        return VDevolucion;
    }
    
    public boolean cerrarConexionBD() {
        boolean VDevolucion;
        
        try {
            this.conexionBD.close();
            
            VDevolucion = true;
        } catch (Exception ex) {
            VDevolucion = false;
        }
        
        return VDevolucion;
        
    }
    // </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menujMantenimientos;
    private javax.swing.JMenuItem opcionCamas;
    private javax.swing.JMenuItem opcionDiagnosticos;
    private javax.swing.JMenuItem opcionHabitaciones;
    private javax.swing.JMenuItem opcionMedicos;
    private javax.swing.JMenuItem opcionPacientes;
    private javax.swing.JMenu opcionSalir;
    private javax.swing.JMenuItem opcionVisitasMedicas;
    // End of variables declaration//GEN-END:variables
}
